name: AKS Deployment
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Configure AKS
        run: az aks get-credentials --resource-group aks-resources --name aks-aks1

      - name: Apply AKS Configuration
        run: kubectl apply -f ./src/app.yaml
