name: Deploy Application to AKS

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Configure AKS
        run: az aks get-credentials --resource-group aks-resources --name aks-aks1

      - name: Build and Push Docker Image
        run: |
          docker build -t krooazurecontainerregistry.azurecr.io/my-image:latest .
          docker login krooazurecontainerregistry.azurecr.io -u ${{ secrets.ACR_USERNAME }} -p ${{ secrets.ACR_PASSWORD }}
          docker push krooazurecontainerregistry.azurecr.io/my-image:latest

      - name: Deploy Application to AKS
        run: kubectl apply -f ./src/app.yaml

